spring.application.name=jobPortal
spring.datasource.url=jdbc:postgresql://localhost:5432/jobs_db
spring.datasource.username=${JOBS_APP_USERNAME}
spring.datasource.password=${JOBS_APP_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true